export { default as NewsResolver } from './NewsResolver'
export { default as TopicResolver } from './TopicResolver'
export { default as AddressResolver } from './AddressResolver'
export { default as InvoiceResolver } from './InvoiceResolver'
export { default as PostResolver } from './PostResolver'
